project:
  type: website
  output-dir: docs

website:
  title: "keisuke-hanada"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: background.qmd
      - href: research.qmd

format:
  html:
    theme: cosmo
    toc: true

lang: ja


