project:
  type: website
  output-dir: docs

website:
  title: "keisuke-hanada"
  google-analytics: "G-80RE24GCEC"
  body-footer: Copyright by Keisuke Hanada
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: background.qmd
      - href: research.qmd
      - href: teaching.qmd


format:
  html:
    theme: cosmo
    toc: true



